/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ta_alpro2;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3330
 */
public class DocData extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    String sql;
    PreparedStatement pstmt;

    public DocData() {
        initComponents();
        initDB();
    }

    private void handlePanel(String name) {
        CardLayout panel = (CardLayout) baseLayout.getLayout();
        panel.show(baseLayout, name);
    }

    private void handleRoles(String role) {
        if (role.equals("Doctor")) {
            handlePanel("panelDoctor");
        } else {
            JLabel[] field = {nama, nik};

            for (JLabel component : field) {
                if (component.getName() != null) {
                    component.setVisible(false);
                    break;
                }
            }

            handlePanel("panelStaff");
        }
    }

    private void initDB() {
        try {
            con = Config.configDB();
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }

    private void loadMedicalRecords() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Dokter");
        model.addColumn("Tanggal Kunjungan");
        model.addColumn("Diagnosis");
        model.addColumn("Treatment");
        model.addColumn("Notes");

        try {
            sql = "SELECT username, s.created_at, diagnosis, treatment, notes FROM medicalrecords s JOIN users u ON u.user_id = s.doctor_id JOIN patients p ON p.patient_id = s.patient_id WHERE p.code = '" + nik.getText() + "'";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),});
            }
            medis_record.setModel(model);
        } catch (Exception e) {
            System.out.println("Gagal Mendapatkan data " + e.getMessage());
        }
    }

    private void clear() {
        p_first_name.setText("");
        p_last_name.setText("");
        p_date_of_birth.setText("");
        p_gender.setSelectedItem("L");
        p_number.setText("");
        p_address.setText("");
        p_email.setText("");
    }

    private void searchPasien(String query) {
        try {
            if (!query.equals("")) {
                sql = "SELECT * FROM patients WHERE first_name LIKE ?";
                pstmt = con.prepareStatement(sql);
                pstmt.setString(1, "%" + query + "%");
                rs = pstmt.executeQuery();

                if (rs.next()) {
                    System.out.print(rs.getString("first_name"));
                    JLabel[] field = {nama, nik};

                    for (JLabel component : field) {
                        if (component.getName() != null) {
                            component.setVisible(true);
                            break;
                        }
                    }

                    notfound.setVisible(false);
                    detail_btn.setEnabled(true);
                    delete_btn.setEnabled(true);
                    edit_btn.setEnabled(true);
                    field[0].setText(rs.getString("first_name"));
                    field[1].setText(rs.getString("code"));
                    rs.close();
                } else {
                    JOptionPane.showMessageDialog(this, "Pasien tidak ditemukan");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Field search tidak boleh kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseLayout = new javax.swing.JPanel();
        panelAuth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panelStaff = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        form_search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        notfound = new javax.swing.JLabel();
        detail_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        panelDoctor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_status = new javax.swing.JButton();
        status_doctor = new javax.swing.JLabel();
        detailPasien = new javax.swing.JPanel();
        heading_detail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        d_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        d_nik = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        d_no = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        d_address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        d_jk = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        d_created = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medis_record = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        createPasien = new javax.swing.JPanel();
        headingForm = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        p_first_name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        p_last_name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        p_date_of_birth = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        p_gender = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        p_number = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        p_address = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        p_email = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DocData");
        setSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseLayout.setLayout(new java.awt.CardLayout());

        panelAuth.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 63, 65));
        jLabel2.setText("Welcome back");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Hopefully recording data will be easier, have a beautiful day");

        email.setText("fahmi@doctor.docdata.id");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 63, 65));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 63, 65));
        jLabel5.setText("Password");

        password.setText("123");

        btnLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnLogin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Forget Password ?");

        javax.swing.GroupLayout panelAuthLayout = new javax.swing.GroupLayout(panelAuth);
        panelAuth.setLayout(panelAuthLayout);
        panelAuthLayout.setHorizontalGroup(
            panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuthLayout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAuthLayout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(304, 304, 304))
            .addGroup(panelAuthLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAuthLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAuthLayout.setVerticalGroup(
            panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAuthLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelAuthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(155, 155, 155))
        );

        baseLayout.add(panelAuth, "panelAuth");

        panelStaff.setBackground(new java.awt.Color(241, 242, 246));
        panelStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Data Pasien");
        panelStaff.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        form_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_searchActionPerformed(evt);
            }
        });
        panelStaff.add(form_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 570, 40));

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelStaff.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 210, 121, 36));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        notfound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notfound.setText("Pasien tidak ditemukan");

        detail_btn.setText("Detail");
        detail_btn.setEnabled(false);
        detail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detail_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.setEnabled(false);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        edit_btn.setText("Edit");
        edit_btn.setEnabled(false);
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nama)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(nik))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notfound)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(detail_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_btn)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(notfound)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama)
                            .addComponent(nik))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detail_btn)
                            .addComponent(delete_btn)
                            .addComponent(edit_btn))
                        .addGap(32, 32, 32))))
        );

        panelStaff.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 710, -1));

        jButton3.setText("Tambah Pasien");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelStaff.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 121, 38));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel46.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel46.setText("Selamat Datang");

        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel47.setText("Dr. Kevin SH.S");

        jLabel48.setText("Foto Doctor");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton10.setText("Logout");

        jButton11.setText("Dashboard");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Data Pasien");

        jButton13.setText("Setting");

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47)
                        .addGap(29, 29, 29)
                        .addComponent(jButton10)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        panelStaff.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 540));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Downloads\\Frame 13 (1) (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelStaff.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        baseLayout.add(panelStaff, "panelStaff");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Status :");

        btn_status.setText("Ready");
        btn_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statusActionPerformed(evt);
            }
        });

        status_doctor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        status_doctor.setForeground(new java.awt.Color(255, 0, 0));
        status_doctor.setText("Not Ready yet");

        javax.swing.GroupLayout panelDoctorLayout = new javax.swing.GroupLayout(panelDoctor);
        panelDoctor.setLayout(panelDoctorLayout);
        panelDoctorLayout.setHorizontalGroup(
            panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctorLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_status)
                    .addGroup(panelDoctorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(status_doctor)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        panelDoctorLayout.setVerticalGroup(
            panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctorLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(status_doctor))
                .addGap(18, 18, 18)
                .addComponent(btn_status)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        baseLayout.add(panelDoctor, "panelDoctor");

        detailPasien.setBackground(new java.awt.Color(241, 242, 246));
        detailPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading_detail.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        heading_detail.setText("Detail Pasien");
        detailPasien.add(heading_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 78, -1, -1));

        jLabel9.setText("Nama Pasien");
        detailPasien.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 131, -1, -1));

        d_name.setEditable(false);
        detailPasien.add(d_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 153, 115, -1));

        jLabel11.setText("Kode Unik");
        detailPasien.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 193, -1, -1));

        d_nik.setEditable(false);
        d_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_nikActionPerformed(evt);
            }
        });
        detailPasien.add(d_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 215, 115, -1));

        jLabel12.setText("No Telepon");
        detailPasien.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 131, -1, -1));

        d_no.setEditable(false);
        detailPasien.add(d_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 153, 115, -1));

        jLabel13.setText("Alamat");
        detailPasien.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 193, -1, -1));

        d_address.setEditable(false);
        detailPasien.add(d_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 215, 115, -1));

        jLabel14.setText("Jenis Kelamin");
        detailPasien.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 249, -1, -1));

        d_jk.setEditable(false);
        detailPasien.add(d_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 271, 115, -1));

        jLabel15.setText("Tanggal Bergabung");
        detailPasien.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 249, -1, -1));

        d_created.setEditable(false);
        d_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_createdActionPerformed(evt);
            }
        });
        detailPasien.add(d_created, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 271, 115, -1));

        medis_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Dokter", "Tanggal Kunjungan", "Diagnosis", "Treatment", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medis_record);

        detailPasien.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 384, 717, 199));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Riwayat Medis");
        detailPasien.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 325, -1, -1));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel49.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel49.setText("Selamat Datang");

        jLabel59.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel59.setText("Dr. Kevin SH.S");

        jLabel60.setText("Foto Doctor");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton22.setText("Logout");

        jButton23.setText("Dashboard");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Data Pasien");

        jButton25.setText("Setting");

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton22)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addGap(29, 29, 29)
                        .addComponent(jButton22)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        detailPasien.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 540));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel61.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Downloads\\Frame 13 (1) (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        detailPasien.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        baseLayout.add(detailPasien, "detailPasien");

        createPasien.setBackground(new java.awt.Color(241, 242, 246));
        createPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headingForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headingForm.setText("Tambah Pasien");
        createPasien.add(headingForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 108, -1, -1));

        jLabel16.setText("First Name");
        createPasien.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 183, -1, -1));
        createPasien.add(p_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 211, 146, 30));

        jLabel17.setText("Last Name");
        createPasien.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 253, -1, -1));

        p_last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_last_nameActionPerformed(evt);
            }
        });
        createPasien.add(p_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 281, 146, 30));

        jLabel18.setText("Tgl Lahir");
        createPasien.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 329, -1, -1));
        createPasien.add(p_date_of_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 357, 146, 30));

        jLabel19.setText("Jenis Kelamin");
        createPasien.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 405, -1, -1));

        p_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        createPasien.add(p_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 433, 146, 30));

        jLabel20.setText("Contact Pasien");
        createPasien.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 183, -1, -1));
        createPasien.add(p_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 211, 151, 30));

        jLabel21.setText("Alamat");
        createPasien.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 253, -1, -1));
        createPasien.add(p_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 281, 151, 30));

        jLabel22.setText("Email");
        createPasien.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 329, -1, -1));
        createPasien.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 357, 151, 30));

        btnSubmit.setText("Tambah");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        createPasien.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 495, 146, 30));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        createPasien.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 495, 121, 30));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel62.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel62.setText("Selamat Datang");

        jLabel63.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel63.setText("Dr. Kevin SH.S");

        jLabel64.setText("Foto Doctor");
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton26.setText("Logout");

        jButton27.setText("Dashboard");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Data Pasien");

        jButton29.setText("Setting");

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel63)
                        .addGap(29, 29, 29)
                        .addComponent(jButton26)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        createPasien.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 540));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel65.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Downloads\\Frame 13 (1) (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        createPasien.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        baseLayout.add(createPasien, "createPasien");
        createPasien.getAccessibleContext().setAccessibleName("");

        getContentPane().add(baseLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            sql = "SELECT email, password, username, role_name FROM users s JOIN roles r ON r.role_id = s.role_id WHERE email = '" + email.getText() + "' AND password='" + password.getText() + "'";
            con = (Connection) Config.configDB();
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);

            if (rs.next()) {
                if (email.getText().equals(rs.getString("email")) && password.getText().equals(rs.getString("password"))) {
                    UserSession.getInstance(rs.getString("username"), rs.getString("role_name"));

                    UserSession session = UserSession.getInstance();
                    handleRoles(session.getRole());
                    rs.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, kombinasi Username dan Password anda salah");
            }

            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        searchPasien(form_search.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void detail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detail_btnActionPerformed
        try {
            handlePanel("detailPasien");
            sql = "select * from patients where code = ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, nik.getText());
            rs = pstmt.executeQuery();

            if (rs.next()) {
                d_name.setText(rs.getString("first_name") + " " + rs.getString("last_name"));
                d_nik.setText(rs.getString("code"));
                d_no.setText(rs.getString("contact_number"));
                d_jk.setText(rs.getString("gender"));
                d_address.setText(rs.getString("address"));
                d_created.setText(rs.getString("created_at"));
                loadMedicalRecords();
            } else {
                System.out.print("Data Tidak Ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_detail_btnActionPerformed

    private void d_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_createdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_createdActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        try {
            handlePanel("createPasien");
            headingForm.setText("Edit Pasien");
            btnSubmit.setText("Update Pasien");

            sql = "select * from patients where code = ?";
            pstmt = con.prepareStatement(sql);
            pstmt.setString(1, nik.getText());
            rs = pstmt.executeQuery();

            if (rs.next()) {
                p_first_name.setText(rs.getString("first_name"));
                p_last_name.setText(rs.getString("last_name"));
                p_date_of_birth.setText(rs.getString("date_of_birth"));
                p_gender.setSelectedItem(rs.getString("gender"));
                p_number.setText(rs.getString("contact_number"));
                p_address.setText(rs.getString("address"));
                p_email.setText(rs.getString("email"));
            } else {
                JOptionPane.showMessageDialog(this, "Pasien tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void btn_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statusActionPerformed

        if (btn_status.getText().equals("Ready") & status_doctor.getText().equals("Not Ready yet")) {
            btn_status.setText("Selesai");
            status_doctor.setText("Ready");
            status_doctor.setForeground(Color.GREEN);
        } else {
            btn_status.setText("Ready");
            status_doctor.setText("Not Ready yet");
            status_doctor.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btn_statusActionPerformed

    private void d_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_nikActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
        handlePanel("createPasien");
        headingForm.setText("Tambah Pasien");
        btnSubmit.setText("Tambah");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void p_last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_last_nameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (headingForm.getText().equals("Tambah Pasien")) {
            try {
                sql = "SELECT code FROM patients ORDER BY code DESC LIMIT 1";
                pstmt = con.prepareStatement(sql);
                rs = pstmt.executeQuery();

                int code = 0;
                if (rs.next()) {
                    code = Integer.parseInt(rs.getString("code"));
                }

                rs.close();

                sql = "INSERT INTO patients (code, first_name, last_name, date_of_birth, gender, contact_number, address, email) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                pstmt = con.prepareStatement(sql);
                pstmt.setInt(1, (code + 1));
                pstmt.setString(2, p_first_name.getText());
                pstmt.setString(3, p_last_name.getText());
                pstmt.setString(4, p_date_of_birth.getText());
                pstmt.setString(5, (String) p_gender.getSelectedItem());
                pstmt.setString(6, p_number.getText());
                pstmt.setString(7, p_address.getText());
                pstmt.setString(8, p_email.getText());
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Pasien Berhasil di Tambah");
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di Tambah " + e.getMessage());
            }
        } else {
            try {
                String sql = "UPDATE patients SET first_name = '" + p_first_name.getText() + "', last_name = '" + p_last_name.getText()
                        + "', date_of_birth = '" + p_date_of_birth.getText() + "', gender = '" + p_gender.getSelectedItem() + "', contact_number = '" + p_number.getText()
                        + "', address = '" + p_address.getText() + "', email = '" + p_email.getText() + "' WHERE code = '"
                        + nik.getText() + "'";
                pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Pasien Berhasil di Edit");

                nama.setText(p_first_name.getText());
                UserSession session = UserSession.getInstance();
                handleRoles(session.getRole());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Perubahan Data Gagal " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        UserSession session = UserSession.getInstance();
        handleRoles(session.getRole());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        try {
            int confirmation = JOptionPane.showConfirmDialog(null, "Apakah kamu benar - benar ingin menghapus pasien ini ?", "Hapus Pasien", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                String sql = "delete from patients where code='" + nik.getText() + "'";
                pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Pasien Berhasil di Hapus");

                nama.setText("");
                nik.setText("");
                notfound.setVisible(true);
                detail_btn.setEnabled(false);
                delete_btn.setEnabled(false);
                edit_btn.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void form_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_searchActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseLayout;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btn_status;
    private javax.swing.JPanel createPasien;
    private javax.swing.JTextField d_address;
    private javax.swing.JTextField d_created;
    private javax.swing.JTextField d_jk;
    private javax.swing.JTextField d_name;
    private javax.swing.JTextField d_nik;
    private javax.swing.JTextField d_no;
    private javax.swing.JButton delete_btn;
    private javax.swing.JPanel detailPasien;
    private javax.swing.JButton detail_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField form_search;
    private javax.swing.JLabel headingForm;
    private javax.swing.JLabel heading_detail;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medis_record;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nik;
    private javax.swing.JLabel notfound;
    private javax.swing.JTextField p_address;
    private javax.swing.JTextField p_date_of_birth;
    private javax.swing.JTextField p_email;
    private javax.swing.JTextField p_first_name;
    private javax.swing.JComboBox<String> p_gender;
    private javax.swing.JTextField p_last_name;
    private javax.swing.JTextField p_number;
    private javax.swing.JPanel panelAuth;
    private javax.swing.JPanel panelDoctor;
    private javax.swing.JPanel panelStaff;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel status_doctor;
    // End of variables declaration//GEN-END:variables
}
